name: Close Snapshot

on:
  pull_request:
    types:
      - closed

jobs:
  Close:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger n8n Snapshot Webhook
        run: |
          curl -X POST https://webhook.eng.sdc.nycu.club/webhook/deploy \
            -H "Content-Type: application/json" \
            -H "x-deploy-token: ${{ secrets.N8N_DEPLOY_TOKEN }}" \
            -d '{
              "source": {
                "title": "Clustron",
                "repo": "${{ github.repository }}",
                "branch": "${{ github.head_ref || github.ref_name }}",
                "commit": "${{ github.sha }}",
                "pr_number": "${{ github.event.pull_request.number }}"
              },
              "method": "cleanup",
              "metadata": {
                "environment": "snapshot",
                "component": "frontend"
              },
              "post": {
                "notify_discord": {
                  "enable": true,
                  "channel": "clustron-activity"
                },
                "cleanup_domain": {
                  "enable": true,
                  "name": "pr-${{ github.event.pull_request.number }}.clustron.sdc.nycu.club"
                }
              }
            }'
